Epic: rename old names for ASF brand Compliance
apache/cloudberry-site pull request #213
Opened 2024-12-17 04:26 UTC by tuhaihe

closes: #ISSUE_Number

---

## Change logs

This commit renames "Cloudberry Database" to "Apache Cloudberry" in the documentation and ensures clarity across references.

## Contributor's checklist

Here are some reminders before you submit your pull request:

* Make sure that your Pull Request has a clear title and commit message. You can take the [Git commit template](https://github.com/apache/cloudberry/blob/main/.gitmessage) as a reference.
* Learn the [code contribution](https://cloudberry.apache.org/contribute/code) and [doc contribution](https://cloudberry.apache.org/contribute/doc) guides for better collaboration.
* Make sure that your changes deployment preview is successful.
* List your communications in the [GitHub Issues](https://github.com/apache/cloudberry-site/issues) or [Discussions](https://github.com/apache/cloudberry/discussions) (if has or needed).
* Feel free to ask for the [cloudberry committers](https://github.com/orgs/apache/teams/cloudberry-committers) or other people to help review and approve.

2024-12-17 04:31 UTC, tuhaihe commented
Will check the files again before merging them.

2024-12-17 06:21 UTC, tuhaihe commented
> In the release notes (both en and zh), the old name "Cloudberry Database" remains unchanged. Is that expected? Besides, you can still get many "Cloudberry Database" search results within this PR branch. ![image](https://private-user-images.githubusercontent.com/41534398/396371857-3a52de10-2aa5-4b43-b05e-661fdd674e9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MTY1MDMsIm5iZiI6MTczNDQxNjIwMywicGF0aCI6Ii80MTUzNDM5OC8zOTYzNzE4NTctM2E1MmRlMTAtMmFhNS00YjQzLWIwNWUtNjYxZmRkNjc0ZTlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDA2MTY0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkMjBkZTg1ZDNmYWNmNDAyODllYmIxMTMyMmIzNzZiZjJlOGYwNDM3NTQwMzgzMGU1OTAyOTEyYjc5ZTk1MmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.e-oPaBFZ4JHx3tNpDWjQrVID-b3iy0Ri-VIgx-7JAss)

For pre-ASF releases, as they are not Apache releases, we cannot rename  
them to Apache Cloudberry. We may consider deleting them after our first  
Apache release, but for now, let's keep them unchanged.

As for other occurrences of "Cloudberry Database" outside the `docs`, I plan  
to update them in a separate PR.

2024-12-17 06:22 UTC, tuhaihe commented on i18n/zh/docusaurus-plugin-content-docs/current/cbdb-linux-compile.md
> +4. [构建 Apache Cloudberry](#第-4-步构建-cloudberry-database)。
Thanks for pointing this out!

2024-12-19 06:10 UTC, edespino requested changes
There are many references to the following which should be updated throughout:

- The old repository name cloudberrydb (in various capitalization forms).
- cloudberrydb.org

2024-12-23 06:07 UTC, tuhaihe commented
> There are many references to the following which should be updated throughout:
> 
> * The old repository name cloudberrydb (in various capitalization forms).
> * cloudberrydb.org

Done. Thanks for your feedback! Please take a look again.

Note: There are still a lot of old links like `https://github.com/cloudberrydb/cloudberrydb-site/blob/cbdb-doc-validation/docs/sql-stmts/release-savepoint.md`. This should be replaced with the new redirect links in the documentation and not included in this PR. I have already created the issue - https://github.com/apache/cloudberry-site/issues/215 for tracking.

2025-03-05 10:14 UTC, closed without merging